services:

  liferay-node1:
    build:
      context: .
      dockerfile: Dockerfile-liferay
    ports:
      - '6080:8080'
    hostname: liferay-node1.local
    environment:
      - CATALINA_OPTS=-Xms25600m -Xmx25600m -XX:MaxPermSize=1024m
    volumes:
      - lfr-dl-volume:/opt/liferay/data/document_library
      - ./deploy/portal-node-1:/opt/liferay/deploy
    depends_on:
      - mysql
      - elasticsearch-node1

  liferay-node2:
    build:
      context: .
      dockerfile: Dockerfile-liferay
    ports:
      - '7080:8080'
    hostname: liferay-node2.local
    volumes:
      - lfr-dl-volume:/opt/liferay/data/document_library
      - ./deploy/portal-node-2:/opt/liferay/deploy
    depends_on:
      - mysql
      - elasticsearch-node1
    profiles:
      - donotstart

  mysql:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: wbEk263dQbwk9jsdbcjw
      MYSQL_DATABASE: lportal
    volumes:
      - mysql-data:/var/lib/mysql

  elasticsearch-node1:
    image: arm64v8/elasticsearch:7.17.20
    environment:
      - cluster.name=elasticsearch
      - node.name=elasticsearch-node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-node1:/usr/share/elasticsearch/data

  haproxy:
    build:
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - '80:80'
    hostname: haproxy.local    
    depends_on:
      - liferay-node1

volumes:
  lfr-dl-volume:
  mysql-data:
  elasticsearch-node1:
