FROM liferay/portal:7.4.3.112-ga112

COPY ./configs/portal-ext.properties $LIFERAY_HOME/
COPY ./configs/*.config $LIFERAY_HOME/osgi/configs/
COPY ./configs/*.jar $LIFERAY_HOME/osgi/portal/
COPY ./configs/setenv.sh $LIFERAY_HOME/tomcat/bin