export CATALINA_OPTS="$CATALINA_OPTS -Xms25600m"
export CATALINA_OPTS="$CATALINA_OPTS -Xmx25600m"
export CATALINA_OPTS="$CATALINA_OPTS -XX:MaxPermSize=1024m"
export CATALINA_OPTS="$CATALINA_OPTS -Dfile.encoding=UTF8"
export CATALINA_OPTS="$CATALINA_OPTS -Djava.net.preferIPv4Stack=true"
export CATALINA_OPTS="$CATALINA_OPTS -Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false"
export CATALINA_OPTS="$CATALINA_OPTS -Duser.timezone=GMT"

CATALINA_OPTS="${CATALINA_OPTS} ${LIFERAY_JVM_OPTS}"